// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";
// import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";




// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({ children }) {

// const {getUser} = getKindeServerSession()
// const user = await getUser();
// console.log(user)


//   return (
//     <html lang="en" className="px-10 py-2">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <nav className="flex justify-between items-center py-4 px-6">
//           {/* Left-side navigation links */}
//           <ul className="flex gap-4">
//             <li>
//               <Link href="/" className="text-gray-700 hover:text-blue-500">
//                 Home
//               </Link>
//             </li>
//             <li>
//               <Link
//                 href="/profile"
//                 className="text-gray-700 hover:text-blue-500"
//               >
//                 Profile
//               </Link>
//             </li>
//           </ul>

//           {/* Right-side Login Button */}
//           <div>
//             <Link
//               href="/api/auth/login"
//               className="bg-blue-500 text-white px-4 py-2 rounded-md text-sm hover:bg-blue-600 transition duration-300"
//             >
//               Login
//             </Link>
//           </div>
//         </nav>
//         {children}
//       </body>
//     </html>
//   );
// }






















// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";
// import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({ children }) {
//   const { getUser } = getKindeServerSession();
//   const user = await getUser();

//   return (
//     <html lang="en" className="px-10 py-2">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <nav className="flex justify-between items-center py-4 px-6">
//           {/* Left-side navigation links */}
//           <ul className="flex gap-4">
//             <li>
//               <Link href="/" className="text-gray-700 hover:text-blue-500">
//                 Home
//               </Link>
//             </li>
//             <li>
//               <Link
//                 href="/profile"
//                 className="text-gray-700 hover:text-blue-500"
//               >
//                 Profile
//               </Link>
//             </li>
//           </ul>

//           {/* Right-side Button */}
//           <div>
//             {user ? ( 
//               <Link
//                 href="/api/auth/logout"
//                 className="bg-red-500 text-white px-4 py-2 rounded-md text-sm hover:bg-red-600 transition duration-300"
//               >
//                 Logout
//               </Link>
//             ) : (
//               <Link
//                 href="/api/auth/login"
//                 className="bg-blue-500 text-white px-4 py-2 rounded-md text-sm hover:bg-blue-600 transition duration-300"
//               >
//                 Login
//               </Link>
//             )}
//           </div>
//         </nav>
//         {children}
//       </body>
//     </html>
//   );
// }










import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kinde Auth App",
  description: "Example of Kinde Auth with Next.js",
};

export default async function RootLayout({ children }) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  console.log("paice",user)

  return (
    <html lang="en" className="px-10 py-2">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#DAE7BA]`}
      >
        <nav className="flex justify-between items-center py-4 px-6">
          <ul className="flex gap-4">
            <li>
              <Link href="/" className="text-gray-700 hover:text-blue-500">
                Home
              </Link>
            </li>
            <li>
              <Link
                href="/profile"
                className="text-gray-700 hover:text-blue-500"
              >
                Profile
              </Link>
            </li>
          </ul>

          <div>
            {user ? (
              <Link
                href="/api/auth/logout" 
                className="bg-red-500 text-white px-4 py-2 rounded-md text-sm hover:bg-red-600 transition duration-300"
              >
                Logout
              </Link>
            ) : (
              <Link
                href="/api/auth/login"
                className="bg-blue-500 text-white px-4 py-2 rounded-md text-sm hover:bg-blue-600 transition duration-300"
              >
                Login
              </Link>
            )}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
